;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        delete-horizontal-space
        electric-newline-and-maybe-indent
        end-of-buffer
        indent-for-tab-command
        kill-region
        kmacro-end-or-call-macro
        kmacro-start-macro-or-insert-counter
        mark-sexp
        move-text-down
        move-text-up
        upcase-region
        wdired--self-insert
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-set-region
        ))
