;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        delete-horizontal-space
        electric-newline-and-maybe-indent
        indent-for-tab-command
        kill-region
        kmacro-end-or-call-macro
        mark-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
